/*
*** MADE BY MITHION'S .SCHEMATIC TO JAVA CONVERTING TOOL v1.6 ***
*/

package vazkii.craftingcreation.area;
import net.minecraft.block.Block;
import net.minecraft.world.World;
import vazkii.craftingcreation.block.ModBlocks;

public class AreaRedBase extends AreaGenerator {

	public static final AreaRedBase INSTANCE = new AreaRedBase();
	
	public AreaRedBase() {
		super(0);
	}

	public void generate(World world, int i, int k) {
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 2, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 3, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 4, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 5, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 7, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 8, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 9, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 10, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 11, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 0, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 2, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 3, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 4, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 5, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 7, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 8, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 9, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 10, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 11, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 1, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 2, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 3, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 4, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 5, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 7, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 8, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 9, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 10, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 11, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 2, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 3, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 4, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 5, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 7, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 8, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 9, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 10, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 11, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 2, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 3, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 4, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 5, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 7, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 8, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 9, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 10, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 11, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 4, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 1, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 2, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 3, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 4, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 5, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 6, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 7, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 8, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 9, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 10, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 11, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 12, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 0, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 3, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 7, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 8, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 9, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 10, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 11, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 3, Block.blockGold.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 2, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 2, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 2, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 3, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 3, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 4, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 4, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 4, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 4, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 5, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 5, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 1, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 1, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 1, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 4, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 4, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 2, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 1, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 0, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 1, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 2, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 4, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 4, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 1, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 1, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 2, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 1, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 1, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 2, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 4, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 4, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 1, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 7, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 0, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 1, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 2, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 4, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 4, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 1, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 7, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 0, k + 13, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 1, k + 13, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 2, k + 13, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 4, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 4, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 7, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 1, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 8, j + 0, k + 13, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 1, k + 13, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 2, k + 13, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 4, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 4, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 1, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 9, j + 0, k + 13, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 1, k + 13, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 2, k + 13, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 4, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 4, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 9, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 0, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 1, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 2, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 4, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 4, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 10, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 0, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 1, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 2, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 4, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 4, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 11, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 2, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 3, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 4, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 5, ModBlocks.creationChest.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 0, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 1, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 1, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 1, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 2, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 2, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 2, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 3, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 3, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 4, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 4, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 4, k + 12, ModBlocks.beacon.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 4, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 5, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 12, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 2, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 3, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 4, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 5, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 7, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 8, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 9, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 10, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 11, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 0, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 2, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 3, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 4, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 5, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 7, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 8, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 9, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 10, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 11, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 1, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 2, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 3, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 4, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 5, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 7, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 8, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 9, ModBlocks.portal.blockID,0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 10, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 11, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 2, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 2, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 3, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 4, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 5, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 7, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 8, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 9, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 10, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 11, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 3, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 0, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 1, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 2, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 3, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 4, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 5, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 6, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 7, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 8, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 9, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 10, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 11, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 12, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 4, k + 13, ModBlocks.creationBricks.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 0, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 1, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 2, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 3, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 4, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 5, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 6, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 7, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 8, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 9, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 10, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 11, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 12, ModBlocks.invisibleWall.blockID, 0, 3);
		world.setBlockAndMetadataWithNotify(i + 13, j + 5, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
		
		for(int y = 6; y < 64; y++) {
			for(int x = 1; x < 13; x++) {
				world.setBlockAndMetadataWithNotify(i + x, j + y, k, ModBlocks.invisibleWall.blockID, 0, 3);
				world.setBlockAndMetadataWithNotify(i + x, j + y, k + 13, ModBlocks.invisibleWall.blockID, 0, 3);
			}
			for(int z = 0; z < 14; z++) {
				world.setBlockAndMetadataWithNotify(i, j + y, k + z, ModBlocks.invisibleWall.blockID, 0, 3);
				world.setBlockAndMetadataWithNotify(i + 13, j + y, k + z, ModBlocks.invisibleWall.blockID, 0, 3);
			}
		}	
	}
}