/*
*** MADE BY MITHION'S .SCHEMATIC TO JAVA CONVERTING TOOL v1.6 ***
*/

package vazkii.craftingcreation.area;
import net.minecraft.world.World;
import vazkii.craftingcreation.block.ModBlocks;

public class AreaTerrainTower extends AreaGenerator {
	
	public AreaTerrainTower() {
		super(2);
	}

	public void generate(World world, int i, int k) {
		world.setBlockAndMetadataWithNotify(i + 0, j + 10, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 0, j + 10, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 0, j + 10, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 0, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 1, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 2, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 2, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 2, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 3, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 3, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 3, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 4, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 4, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 5, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 5, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 5, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 6, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 6, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 6, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 7, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 7, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 7, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 8, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 8, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 8, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 9, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 9, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 9, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 10, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 10, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 10, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 10, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 10, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 0, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 1, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 1, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 1, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 3, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 3, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 4, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 4, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 4, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 5, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 5, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 5, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 6, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 6, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 7, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 7, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 8, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 8, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 9, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 9, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 9, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 9, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 9, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 10, k + 0, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 10, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 10, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 10, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 10, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 10, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 2, j + 10, k + 6, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 2, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 2, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 5, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 5, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 6, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 6, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 7, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 7, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 7, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 8, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 8, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 8, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 8, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 9, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 9, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 9, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 9, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 10, k + 0, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 10, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 10, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 10, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 3, j + 10, k + 6, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 0, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 1, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 1, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 2, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 2, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 2, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 3, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 3, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 3, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 4, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 5, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 5, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 6, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 6, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 6, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 7, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 7, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 7, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 7, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 8, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 8, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 8, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 9, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 9, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 9, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 10, k + 0, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 10, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 10, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 10, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 10, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 10, k + 6, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 0, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 1, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 1, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 2, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 2, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 2, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 3, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 3, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 3, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 4, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 4, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 6, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 6, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 6, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 7, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 7, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 7, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 8, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 8, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 8, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 9, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 9, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 9, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 10, k + 1, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 10, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 10, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 10, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 10, k + 5, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 6, j + 10, k + 2, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 6, j + 10, k + 3, ModBlocks.creationBricks.blockID, 0, 2);
		world.setBlockAndMetadataWithNotify(i + 6, j + 10, k + 4, ModBlocks.creationBricks.blockID, 0, 2);
	}
}